version: '3.9'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: portfolio
    container_name: portfolio
    ports:
      - 8000:8000
    volumes:
      - .:/app/
      - static_vol:/app/index/static/
    command: 'gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000'

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/index/static/
    ports:
      - 80:80
    depends_on:
      - django_app

volumes:
  static_vol: 