version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio
    container_name: portfolio
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    expose:
      - 8000
    command: 'python manage.py runserver 0.0.0.0:8000'
networks:
  default:
    name: development
    external: true