# Generated by Django 4.1.5 on 2023-01-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_userdata_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
